---
title: "Métataxonomie des bactéries du fromage"
author: [Gustavo Magaña López, Théo Roncalli]
date: "18/11/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
set.seed(1234)
```

```{r lib.import}
# CRAN
.required.packages <- 
  c("rlang", "tidyverse", "reshape2", "parallel", "foreach", 
    "doParallel", "stringr", "doRNG", "here", "devtools", 
    "docstring")

new.packages <- 
  .required.packages[!(.required.packages %in% installed.packages()[,"Package"])]

if(length(new.packages)) { install.packages(new.packages) } 

.loaded <- lapply(.required.packages, require, character.only = T)

if (!require("matR")){ install_github(repo='MG-RAST/matR',quiet=T) }

source(here("TP1/tp_utility_functions.R"))
```

```{r data.import}
# Read raw data, the initial dot implies these objects are not 
# supposed to be used directly
# The identifier should be read as a string 
.metadata.df <- within(read.table("MetadataCheese.csv", header = T), {
  ID <- as.character(ID)
})
.metadata.tb <- tibble(.metadata.df)

# use a backup file to avoid performing a 
# web request each time we run the code / compile the report
.backup.file <- "biom_phylum.rds"
if (!file.exists(.backup.file)){
  #List des accessions associées à l'étude mgp3362 
  # (2 échantillons absents des métadonnées)
  list_mgp3362 <- metadata("mgp3362")$mgp3362
  list_mgp3362 <- list_mgp3362[c(-11,-22)]
  #Récupération des données taxonomiques (request='organism') depuis les hits
  #de la base de données RDP (source='RDP') au niveau de l'ordre (group_level='order')
  #avec une evalue de 1e-15 (evalue=15)
  biom_phylum <- biomRequest(
    list_mgp3362, request="organism", source="RDP",
    group_level="order", evalue=15, wait=TRUE
  )
  saveRDS(biom_phylum, .backup.file)
} else {
  biom_phylum <- readRDS(.backup.file)
}

# Coerce into matrix. initial dot indicates 
# we are unsure if this has the right format and data
# is consistent and meaningful (hint: it is not)
.phylum.matrix <- as.matrix(biom_phylum)

.clean <- clean_data_frame(.phylum.matrix)
phylum.df <- .clean$clean.df
phylum.matrix <- as.matrix(phylum.df)
phylum.tb <- phylum.df %>% rownames_to_column("Strain") %>% as_tibble()


.null.cols.chr <- .clean$null.cols %>% 
  # this regex matches numbers with at least one decimal, 
  # preceded by three letters (as our IDs are conigured)
  # letters are not captured
  str_match("(?<=[:alpha:]{3})[:digit:]+\\.[:digit:]+") %>% 
  as.character()

metadata.tb <- .metadata.tb %>% filter(!ID %in% .null.cols.chr)
metadata.df <- metadata.tb %>% column_to_rownames("ID")
```


Les courbes de raréfaction doivent être par échantillon.

```{r rarefaction.curve, cache=T}
otus <- phylum.df %>% rownames
samples <- phylum.df %>% colnames
phylum.prob.df <- apply(phylum.df, 2, function(x){ x / sum(x)})


.n.replicas <- 500
if (!file.exists(here("TP1/rarefactions.csv"))){
  library(doParallel)
  cl <- makeCluster(parallel::detectCores())
  registerDoParallel(cl)
  set.seed(1234)
  
  tryCatch(
    rarefactions.tb <- foreach(
      i=samples, .inorder = F, .combine = rbind, 
      .packages = c("magrittr", "tibble", "stringr")
    ) %dorng% {
      .nb.seq <- seq(1, sum(phylum.df[,i]), 20)
      .n.taxa <- vector("numeric", length = length(.nb.seq))
      for (j in seq_along(.nb.seq)){
       .n.taxa[j] <- replicate(.n.replicas, 
         sample(otus, .nb.seq[j], prob = phylum.prob.df[,i], replace = T) %>% 
           unique %>% length
        ) %>% mean
      }
      tibble(
        `Nombre de Séquences`=.nb.seq, 
        `Nombre d'OTU`=.n.taxa,
        `Échantillon`=i %>% 
          str_match("(?<=[:alpha:]{3})[:digit:]+") %>% 
          as.character()
      )
    }, 
    finally = stopCluster(cl)
  )
} else {
  rarefactions.tb <- read_csv(here("TP1/rarefactions.csv"), col_types = "nnc")
}



rarefactions.tb %>% 
  ggplot(aes(x=`Nombre de Séquences`, y=`Nombre d'OTU`)) +
    geom_line(aes(colour=`Échantillon`)) + 
      labs(title = glue::glue("Diversité alpha, moyenne sur {.n.replicas} répliques")) +
        theme_classic()
```

```{r shannon}
shannon <- apply(phylum.prob.df, 2, H)

shannon.df <- shannon %>% as.data.frame()
colnames(shannon.df) <- c("H")

write.csv(shannon.df, file = here("H.csv"))

.are.aligned <- metadata.tb %>% 
  mutate(
    `Shannon Entropy` = shannon, 
    `Shannon ID` = str_replace(names(shannon), "mgm", "")
  ) %>% 
  filter(ID == `Shannon ID`) %>% 
  nrow == nrow(metadata.tb)

stopifnot(.are.aligned)

# .r suffix indicates it will be used for regression
metadata.tb.r <- metadata.tb %>% 
  mutate(
    `Shannon Entropy` = shannon, 
    RindType = factor(RindType),
    Pasteurized = factor(Pasteurized),
    Country = factor(Country),
    Region = factor(Region),
    Milk = factor(Milk)
  )

metadata.tb.r %>% 
  ggplot(aes(x=pH, y=`Shannon Entropy`)) + 
  geom_point(aes(colour=RindType, shape = Milk, size=NaCl))

# I did this regression because if we try with all variables, the problem
# is undetermined
reg1 <- lm(`Shannon Entropy` ~ RindType + pH + NaCl + Pasteurized + Milk + Moisture, 
   data = metadata.tb.r)
s.reg1 <- summary(reg1)

shannonreg <- s.reg1$coefficients %>% 
  as.data.frame %>% rownames_to_column() %>% 
  as_tibble() %>% 
  mutate( `Significatif` = if_else(`Pr(>|t|)` < 0.05, "Oui", "Non")) %>%
  rename(`p-value` = `Pr(>|t|)`)
  rename(Variable = rowname)


write.csv(shannonreg, file = here("shannonreg.csv"))
write.cs
```


```{r pca.lda}
#Chargement du package MASS
library(MASS)
## NB la matrice de données doit être transformée
LDA<-lda(x=t(phylum.matrix),grouping=metadata.df$Pasteurized)

## Calcul des valeurs pour chaque groupe
LDA1_RawMilk <- colSums(apply(phylum.matrix[,metadata.df$Pasteurized=='N'],2,
function(x){LDA$scaling*x}))

LDA1_Pasteurized<-colSums(apply(phylum.matrix[,metadata.df$Pasteurized=='Y'],2,
function(x){LDA$scaling*x}))

#Représentation sous forme d'histogramme
plot.new()
hist(LDA1_Pasteurized, xlim=c(min(LDA1_RawMilk)-4, max(LDA1_Pasteurized)+1),
     col='green', xlab='LD1 means', ylab='Frequency', main='Predicted Values'
)

plot.new()
hist(LDA1_RawMilk,col='red',add=T)
legend('topleft',pch=19,col=c('red','green'),legend = c('Raw','Pasteurized'))

```

Faites maintenant la même analyse discriminante sur les variables 
catégorielles du type de croûte et de lait.

```{r tidy.ldas}
lda_pasteurized <- 
  tidy_lda(phylum.matrix, metadata.tb, Pasteurized)

rind.meta <- metadata.tb %>% 
  mutate(RindMod = if_else(RindType == "washed", RindType, "unwashed"))
lda_rindtype <- 
  tidy_lda(phylum.matrix, rind.meta, RindMod)

lda_milk <- 
  tidy_lda(phylum.matrix, metadata.tb, Milk)

ldas <- list()

ldas[[1]] <- lda_pasteurized$visual %>% 
  ggplot(aes(x=LDA_means, fill=Group)) + 
  geom_histogram(aes(y=..density..), alpha=0.5, 
                 position="identity", colour="black", bins = 24) +
  #geom_histogram(alpha=0.5, position="identity", bins = 24) +
  labs(title = "Pasteurized")
  
ldas[[2]] <- lda_rindtype$visual %>% 
  ggplot(aes(x=LDA_means, fill=Group)) + 
  geom_histogram(aes(y=..density..), alpha=0.3, position="identity", 
                 colour="black", bins = 24) +
  labs(title = "Rind Type")
  
  
ldas[[3]] <- lda_milk$visual %>% 
  ggplot(aes(x=LDA_means, fill=Group)) + 
  geom_histogram(aes(y=..density..), alpha=0.5, position="identity", colour="black", bins = 24) +
  labs(title = "Milk Type")

gridExtra::grid.arrange(ldas[[1]], ldas[[2]], ldas[[3]], nrow=1)
#do.call(gridExtra::grid.arrange, ldas)
```

```{r tablo}
milk.lda.scaling <-
  lda_milk$model$scaling[,1] %>% sort(decreasing = T) %>% as.data.frame() 
rind.lda.scaling <- 
  lda_rindtype$model$scaling[,1] %>% sort(decreasing = T) %>% as.data.frame()
past.lda.scaling <-
  lda_pasteurized$model$scaling[,1] %>% sort(decreasing = T) %>% as.data.frame()

scalings <- cbind(past.lda.scaling, milk.lda.scaling, rind.lda.scaling)
colnames(scalings) <- c("Milk ~", "Rind ~", "Pasteurized ~")
scalings %>% knitr::kable(digits = 4)
write.csv(scalings, file = here("lda_scalings_from_taxa2.csv"))
```


```{r other.plot}
par(mar=c(15,5,5,5))
barplot(LDA$scaling[,1],names.arg = rownames(LDA$scaling),las=2,
col='black',cex.names = 0.76)
```


```{r acp}
#lda(x=t(phylum_matrix),grouping=metadata$Pasteurized)
pca_res <- acp <- prcomp(t(phylum.prob.df), scale = F)
biplot(acp)
acp$x[,1:2] %>% as.data.frame() %>% ggplot(aes(PC1, PC2)) + geom_point()

var_explained <- pca_res$sdev^2/sum(pca_res$sdev^2)
pca_res$x %>% 
  as.data.frame %>%
  ggplot(aes(x=PC1,y=PC2)) + geom_point(size=4) +
  theme_bw(base_size=32) + 
  labs(x=paste0("PC1: ",round(var_explained[1]*100,1),"%"),
       y=paste0("PC2: ",round(var_explained[2]*100,1),"%")) +
  theme(legend.position="top")
```


```{r diversite.lm.taxa}
phylum.matrix.t <- t(phylum.matrix)

coherent.lm <- function(Y, X){
  
  skip.first <- function(x){ x[2:length(x)] }
  
  .first.lm <- lm(Y ~ X)
  .to.keep <- skip.first(!is.na(.first.lm$coefficients))
  .. <- X[, .to.keep]
  
  .model <- lm(Y ~ ..)
  names(.model$coefficients) <-
    .model$coefficients %>% 
    names %>% 
    stringr::str_replace("\\.\\.", "")
  .model
}

toppres <- rowSums(phylum.df) %>% 
  sort(decreasing = T) %>% 
  as.data.frame() %>% 
  head(10)

our.taxa <- Filter(function(x){ !str_detect(x, "unclassified")}, row.names(toppres))

nacl <- coherent.lm(Y = metadata.df$NaCl, phylum.matrix.t[, our.taxa])
moist <- coherent.lm(Y = metadata.df$Moisture, phylum.matrix.t[, our.taxa])
ph <- coherent.lm(Y = metadata.df$pH, phylum.matrix.t[, our.taxa])


nacl.coefs <- summary(nacl)$coefficients %>%   # %>% sort(decreasing = T) %>% as.data.frame()
  as.data.frame %>% rownames_to_column() %>% 
  as_tibble() %>% 
  mutate( `Significatif` = if_else(`Pr(>|t|)` < 0.05, "Oui", "Non")) %>%
  rename(`p-value` = `Pr(>|t|)`) %>% 
  rename(Variable = rowname)
  
moist.coefs<- summary(moist)$coefficients %>% 
  as.data.frame %>% rownames_to_column() %>% 
  as_tibble() %>% 
  mutate( `Significatif` = if_else(`Pr(>|t|)` < 0.05, "Oui", "Non")) %>%
  rename(`p-value` = `Pr(>|t|)`) %>% 
  rename(Variable = rowname)# %>% sort(decreasing = T) %>% as.data.frame()

ph.coefs <- summary(ph)$coefficients %>% 
  as.data.frame %>% rownames_to_column() %>% 
  as_tibble() %>% 
  mutate( `Significatif` = if_else(`Pr(>|t|)` < 0.05, "Oui", "Non")) %>%
  rename(`p-value` = `Pr(>|t|)`) %>% 
  rename(Variable = rowname)# %>% sort(decreasing = T) %>% as.data.frame()

write.csv(nacl.coefs, "nacl.csv")
write.csv(moist.coefs, "moist.csv")
write.csv(ph.coefs, "ph.csv")

#coefs <- cbind(ph.coefs, nacl.coefs, moist.coefs)
#colnames(coefs) <- c("pH ~", "NaCl ~", "Moisture ~")
#write_csv(x = coefs, file = here("coefs_taxa.csv"))
```

